// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13vEYr351wDuy6w-q9d-zXG-OGKLf-YQ',
    appId: '1:788506207585:web:59530b50d2a7b9a6b4d120',
    messagingSenderId: '788506207585',
    projectId: 'food-recipes-dc442',
    authDomain: 'food-recipes-dc442.firebaseapp.com',
    storageBucket: 'food-recipes-dc442.appspot.com',
    measurementId: 'G-SVW2RESTTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxDuutlI1fUMQxan1tW4NXMlUActyilxk',
    appId: '1:788506207585:android:6e96587ad8d22448b4d120',
    messagingSenderId: '788506207585',
    projectId: 'food-recipes-dc442',
    storageBucket: 'food-recipes-dc442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2yqeHKwmZQGEowyJwflheNX4-frCF80Y',
    appId: '1:788506207585:ios:fb8651de075e1abab4d120',
    messagingSenderId: '788506207585',
    projectId: 'food-recipes-dc442',
    storageBucket: 'food-recipes-dc442.appspot.com',
    iosBundleId: 'com.example.foodRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2yqeHKwmZQGEowyJwflheNX4-frCF80Y',
    appId: '1:788506207585:ios:fb8651de075e1abab4d120',
    messagingSenderId: '788506207585',
    projectId: 'food-recipes-dc442',
    storageBucket: 'food-recipes-dc442.appspot.com',
    iosBundleId: 'com.example.foodRecipes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD13vEYr351wDuy6w-q9d-zXG-OGKLf-YQ',
    appId: '1:788506207585:web:9b0c1e9f0d51aae0b4d120',
    messagingSenderId: '788506207585',
    projectId: 'food-recipes-dc442',
    authDomain: 'food-recipes-dc442.firebaseapp.com',
    storageBucket: 'food-recipes-dc442.appspot.com',
    measurementId: 'G-Z0TSL5WJB4',
  );
}
